# Site settings.
# This is where you can put site-wide settings.
# Any values placed here are globally accessible
# from any template context via the `site` key.
site:
  title: Complete Intro to React
  email:
  description: > # this means to ignore newlines until "baseurl:"
    A Complete Intro to React, as taught for FrontendMasters.com
  baseurl: "" # the subpath of your site, e.g. /blog
  url: "https://btholt.github.io/complete-intro-to-react" # the base hostname & protocol for your site

# Where things are.
# If you have a unique layout for your site and want to
# change where Reptar looks for certain files you can change
# them here. All files are relative to where the `_config.yml`
# is found.
path:
  source:      ./
  destination: ./_site
  plugins:     ./_plugins
  themes:      ./_themes
  data:        ./_data

# Individual File configuration.
file:
  # What key from a File's frontmatter Reptar should use
  # as the property to grab the URL of the file from.
  url_key: url
  # The format that your date values are formatted as.
  # This is used when parsing date objects.
  # This current format supports dates like 2016-2-28
  # It uses moment.js under the head and its format syntax as well:
  # http://momentjs.com/docs/#/displaying/format/
  date_format: YYYY-M-D
  # Apply frontmatter values to a File based upon a defined scope.
  # If the scope matches a File then the default values are applied if they
  # are not already set.
  defaults:
    -
      scope:
         # Any file in this path will have the default values applied.
         path: ./
      values:
        template: page
        permalink: /:title/
    -
      scope:
         # Any file in this path will have the default values applied.
         # Because this path is more specific it will over-write the previous
         # defaults.
         path: ./_posts
      values:
        template: post
        permalink: /:title/
    -
      scope:
         # Any file with this matching metadata will have the default values applied.
         metadata:
           draft: true
      values:
        template: draft
  # Filter out Files.
  filters:
    # If any of the metadata values match then the File is filtered out.
    metadata:
      draft: true
    # If the date is in the future then it is filtered out.
    future_date:
      # Customize what key we should use to pull the date value from.
      key: date

# This is where you configure your collections of content.
# For more details refer to the Collections documentation.
collections:
  post:
    path: ./_posts
    template: index
    page_size: 100
    sort:
      key: date
      order: ascending
    permalink:
      index: /
      page:  /page/:page/
  tag:
    metadata: tags
    template: tag
    page_size: 6
    sort:
      key: date
      order: descending
    permalink:
      index: /tag/:metadata/
      page:  /tag/:metadata/:page/

# Current theme.
# What theme your Reptar site should use when building your site.
theme: 'citr'

# If we should remove the compile destination folder before writing.
clean_destination: false

# Slug options.
# Options passed to node-slug
slug:
  lower: true

# Markdown.
# This lets you customize how markdown is handled.
markdown:
  # What file extensions we should recognize as a markdown file.
  extensions:
    - markdown
    - mkdown
    - mkdn
    - mkd
    - md
  # Options given directly when creating our markdown parser.
  # Documentation here:
  # https://github.com/markdown-it/markdown-it#init-with-presets-and-options
  options:
    preset:       'commonmark'
    highlight:    true

# Serving.
# When running `reptar serve` what settings should be used.
server:
  port:    8010
  host:    127.0.0.1
  baseurl: "" # does not include hostname

# Only build files that have changed.
# This is a performance improvement to the time it takes to build your site.
incremental: true

# Where files created via `reptar new` should be placed.
new_file_permalink: '/_posts/:date|YYYY-:date|MM-:date|D-:title.md'

# What plugins you want enabled and what configuration settings they should have.
plugins:
  html-minifier:
    enabled: false
    options:
      collapseWhitespace: true
      collapseBooleanAttributes: true
      removeAttributeQuotes: true
  excerpt:
    enabled: true
